name: run-netcdf-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  netcdf_test:
    name: netcdf test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt -yq install $(<netcdf_examples/dependencies_ncdf)
            nc-config --version
      - name: Build and run quantize test
        run: |
            python3 -m unittest discover -v -s netcdf_examples/
        shell: bash